Repository TeamOmoolen/TeamOmoolen-Server, pull requests merged in 2021-07, with the labels that each got.

#9 [Fix] maximum call stack size exceeded 에러 해결
  src/entities/Products.ts
Labels: fix

#14 [Chore] Products Entity -> color 필드 타입 변경
  src/entities/Products.ts
Labels: chore

#15 [Fix] JWT Token을 통한 Request 유저 확인 에러 해결
  src/common/decorators/user.decorator.ts
  src/entities/Users.ts
  src/entities/embedded/SuitedLens.ts
  src/entities/embedded/WantedLens.ts
  src/middlewares/auth.middleware.ts
Labels: chore, fix

#16 [Feat] 발견탭 눌렀을 때 탭별 추천 상품 목록 전달 구현
  package-lock.json
  package.json
  src/common/decorators/user.decorator.ts
  src/main.ts
  src/products/products.controller.ts
  src/suggest/dto/suggestProduct.reponse.dto.ts
  src/suggest/suggest.controller.ts
  src/suggest/suggest.module.ts
  src/suggest/suggest.service.ts
  src/users/users.service.ts
Labels: feat

#18 [Feat] 발견탭-ForYou/상황/New/계절별 추천상품 목록 API
  src/suggest/dto/suggestProduct.reponse.dto.ts
  src/suggest/suggest.controller.ts
  src/suggest/suggest.module.ts
  src/suggest/suggest.service.ts
Labels: feat

#19 [Feat] 발견탭 상품 정렬 구현
  src/suggest/suggest.controller.ts
  src/suggest/suggest.service.ts
Labels: feat

#20 [merge] 상세페이지 API, 발견뷰 API 구현 완료
  src/entities/Products.ts
  src/entities/embedded/WantedLens.ts
  src/products/products.controller.ts
  src/products/products.service.ts
  src/suggest/suggest.controller.ts
  src/suggest/suggest.service.ts
Labels: feat, fix

#23 [REFACTOR] - Response body format changed
  src/app.controller.ts
  src/app.service.ts
Labels: refactor

#24 [Merge] 홈뷰/검색 API 리팩토링
  src/app.controller.ts
  src/app.service.ts
  src/common/dto/filter.condition.dto.ts
  src/common/dto/home.value.dto.ts
  src/common/dto/save.onboarding.data.dto.ts
  src/entities/Guides.ts
  src/entities/Users.ts
  src/suggest/suggest.service.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: refactor

#25 [Feat] Kakao Login For Android 구현 -> isNewUser Boolean 값 넘겨주기
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
Labels: feat

#26 [Add] app.controller에 AuthGuard 적용
  src/app.controller.ts
Labels: add

#27 [Chore] changeCycle 필드 변경
  .env
  src/app.service.ts
  src/common/dto/guide.home.dto.ts
  src/common/dto/home.value.dto.ts
  src/common/dto/newLensBrand.dto.ts
  src/entities/Products.ts
  src/products/dto/product-detail.response.dto.ts
  src/products/products.controller.ts
  src/products/products.service.ts
  src/suggest/suggest.service.ts
Labels: chore

#28 [Chore] 컨트롤러 라우팅 설정 변경 (/api) 추가
  src/auth/auth.controller.ts
  src/products/products.controller.ts
  src/suggest/suggest.controller.ts
  src/users/users.controller.ts
Labels: chore

#30 [Merge] Config 파일 분리, .env 파일 제거
  .env
  src/auth/auth.controller.ts
Labels: chore

#31 AuthKey 파일 S3 업로드
  src/auth/auth.controller.ts
Labels: chore

#32 [Del] 불필요한 UseGuard 제거
  src/app.controller.ts
  src/app.service.ts
Labels: delete

#33 [Add] findSuggestProduct 함수에서 유저의 wearTime, season도 리턴 추가
  src/suggest/suggest.service.ts
Labels: add

#37 [Fix] searchWindow controller 예외처리
  src/app.controller.ts
Labels: fix

#39 [Fix] 예외처리 코드 추가, 페이징 변수 수정
  src/app.controller.ts
  src/products/products.controller.ts
  src/suggest/suggest.controller.ts
  src/suggest/suggest.service.ts
  src/users/users.controller.ts
Labels: fix

#40 [Add] 온보딩 컨트롤러 Guard 추가
  src/users/users.controller.ts
Labels: add

#41 [Fix] Apple AuthKey 위치 이동
  src/auth/auth.controller.ts
Labels: fix

#42 [Fix] 애플 로그인 토큰 에러 해결시도 #1
  src/auth/auth.controller.ts
Labels: try

#43 [Fix] 애플 로그인 토큰 에러 해결시도 #2
  src/auth/auth.controller.ts
Labels: try

#44 [Fix] 검색/필터검색 API 페이징 변수, response 수정
  src/app.service.ts
Labels: fix

#46 [Chore] 클라이언트 요청에 따른 findNewLens response 구조 수정
  src/app.service.ts
Labels: chore

#47 [Fix] 필터검색 클라이언트 연결 시도 #1
  src/app.controller.ts
  src/app.service.ts
Labels: try

#48 [Fix] 필터검색 클라이언트 연결 시도 #2
  src/app.controller.ts
  src/app.service.ts
Labels: fix

#49 [Fix] 필터검색 클라이언트 연결 시도 #3
  src/app.controller.ts
Labels: try

#51 [Add] 검색/필터검색 정렬 API 적용
  src/app.service.ts
Labels: add

#52 [Fix] suggestForSituation switch문 break 추가
  src/suggest/suggest.service.ts
Labels: fix

#53 [ADD] - 같은 상품 추천 제외
  src/products/products.service.ts
Labels: add

#54 [Chore] 클라이언트 요청에 따른 발견탭 API 요청 response 구조 변경 -> totalPage 추가
  src/common/dto/suggest.response.dto.ts
  src/suggest/suggest.service.ts
Labels: chore
